---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod-db01
  domain: spylight.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: postgresql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-81fe70a2
  image_type: m3.xlarge
  image_id: ami-5ffaa636
  security_groups:
  - spylight_production_default
  - spylight_production_prod-db01
  - spylight_production_postgresql_master
  - spylight_production_postgresql
  - spylight_production_db
  - spylight_production_collectd
  - spylight_production_monit
  external_host: ec2-54-198-87-124.compute-1.amazonaws.com
  external_ip: 54.198.87.124
  internal_host: ip-10-146-236-156.ec2.internal
  internal_ip: 10.146.236.156
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod-web01
  domain: spylight.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-60f77943
  image_type: m3.large
  image_id: ami-5ffaa636
  security_groups:
  - spylight_production_default
  - spylight_production_prod-web01
  - spylight_production_web
  - spylight_production_haproxy
  - spylight_production_collectd
  - spylight_production_monit
  external_host: ec2-54-82-218-227.compute-1.amazonaws.com
  external_ip: 54.82.218.227
  internal_host: ip-10-63-28-146.ec2.internal
  internal_ip: 10.63.28.146
  zone: us-east-1b
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod-tools
  domain: spylight.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graylog_elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-e9f3c4b9
  image_type: m1.medium
  image_id: ami-5ffaa636
  security_groups:
  - spylight_production_default
  - spylight_production_prod-tools
  - spylight_production_web_tools
  - spylight_production_apache
  - spylight_production_graphite_server
  - spylight_production_graphite_web
  - spylight_production_graylog_web
  - spylight_production_graylog_server
  - spylight_production_graylog_mongodb
  - spylight_production_mongodb
  - spylight_production_graylog_elasticsearch
  - spylight_production_elasticsearch
  - spylight_production_collectd
  - spylight_production_monit
  external_host: ec2-54-234-0-237.compute-1.amazonaws.com
  external_ip: 54.234.0.237
  internal_host: ip-10-212-102-149.ec2.internal
  internal_ip: 10.212.102.149
  zone: us-east-1d
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod-app03
  domain: spylight.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_scheduler
    options: {}
  instance_id: i-3c934a17
  image_type: c3.2xlarge
  image_id: ami-5ffaa636
  security_groups:
  - spylight_production_default
  - spylight_production_prod-app03
  - spylight_production_app
  - spylight_production_passenger
  - spylight_production_apache
  - spylight_production_collectd
  - spylight_production_monit
  external_host: ec2-23-20-78-120.compute-1.amazonaws.com
  external_ip: 23.20.78.120
  internal_host: ip-10-225-150-170.ec2.internal
  internal_ip: 10.225.150.170
  zone: us-east-1c
  provider: aws
  platform: linux
  root_device_type: instance-store
- !ruby/object:Rubber::Configuration::InstanceItem
  name: prod-app04
  domain: spylight.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: apache
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_scheduler
    options: {}
  instance_id: i-25944d0e
  image_type: c3.2xlarge
  image_id: ami-5ffaa636
  security_groups:
  - spylight_production_default
  - spylight_production_prod-app04
  - spylight_production_app
  - spylight_production_passenger
  - spylight_production_apache
  - spylight_production_collectd
  - spylight_production_monit
  external_host: ec2-54-91-246-196.compute-1.amazonaws.com
  external_ip: 54.91.246.196
  internal_host: ip-10-203-170-70.ec2.internal
  internal_ip: 10.203.170.70
  zone: us-east-1c
  provider: aws
  platform: linux
  root_device_type: instance-store
- volumes: {}
  static_ips: {}
